#!/bin/bash

# demander le mot de passe
echo -n "Entrez le mot de passe : "
read -s password
echo

# demander le mot de passe une deuxième fois
echo -n "Entrez le mot de passe à nouveau : "
read -s password2   
echo

# vérifier si les deux mots de passe sont identiques
if [ "$password" != "$password2" ]; then
    echo "Les mots de passe ne correspondent pas."
    exit 1
fi  

# créer un fichier contenant le mot de passe encrypté
echo $password | openssl enc -aes-256-cbc -a -salt -pbkdf2 -iter 100000 -pass pass:password > password

echo "Mot de passe configuré avec succès."
